services:
  app:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: loja-mvc-app
    working_dir: /workspace
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - mongo
    environment:
      MAVEN_CONFIG: /tmp/.m2
      MONGO_URI: mongodb://mongo:27017/loja_mvc
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace
      - ${HOME}/.m2:/tmp/.m2
    command: mvn -Dmaven.repo.local=/tmp/.m2/repository spring-boot:run

  mongo:
    image: mongo:7
    container_name: loja-mvc-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
